In [2]:
import pandas as pd
import numpy as np  

In [3]:
df = pd.read_excel("./data/Document from yash.xlsx")

In [4]:
df.head()

Age  Gender                         Stream  Internships  CGPA  Hostel  \
0   22    Male  Electronics And Communication            1     8       1   
1   21  Female               Computer Science            0     7       1   
2   22  Female         Information Technology            1     6       0   
3   21    Male         Information Technology            0     8       0   
4   22    Male                     Mechanical            0     8       1   

   HistoryOfBacklogs  PlacedOrNot  
0                  1            1  
1                  1            1  
2                  0            1  
3                  1            1  
4                  0            1

In [5]:
from sklearn.preprocessing import LabelEncoder

label = LabelEncoder()
df['Gender'] = label.fit_transform(df['Gender'])
df['Stream'] = label.fit_transform(df['Stream'])

In [6]:
df.corr()

Age    Gender    Stream  Internships      CGPA  \
Age                1.000000  0.040671 -0.022889    -0.022917  0.006845   
Gender             0.040671  1.000000 -0.025856    -0.128163  0.020981   
Stream            -0.022889 -0.025856  1.000000    -0.026956  0.019010   
Internships       -0.022917 -0.128163 -0.026956     1.000000 -0.050097   
CGPA               0.006845  0.020981  0.019010    -0.050097  1.000000   
Hostel            -0.042972 -0.178032  0.275264     0.024383 -0.028760   
HistoryOfBacklogs -0.079167  0.018740  0.052424    -0.021266  0.019368   
PlacedOrNot        0.145218  0.035910  0.070176     0.153479  0.501089   

                     Hostel  HistoryOfBacklogs  PlacedOrNot  
Age               -0.042972          -0.079167     0.145218  
Gender            -0.178032           0.018740     0.035910  
Stream             0.275264           0.052424     0.070176  
Internships        0.024383          -0.021266     0.153479  
CGPA              -0.028760           0.019368     0.501089  
Hostel             1.000000           0.101767    -0.028146  
HistoryOfBacklogs  0.101767           1.000000    -0.026320  
PlacedOrNot       -0.028146          -0.026320     1.000000

In [7]:
import pandas as pd
import numpy as np
corr = df.corr()
corr.style.background_gradient(cmap='coolwarm')

In [8]:
X = df.iloc[: , :-1]
y = df.iloc[:,-1:]

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train , X_test , y_train , y_test = train_test_split(X, y ,test_size=0.2, random_state=42)

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [13]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
X, y = make_classification(n_samples=1000, n_features=7,
                           n_informative=2, n_redundant=0,
                           random_state=0, shuffle=True)
clf = RandomForestClassifier(max_depth=2, random_state=0)
clf.fit(X_train_scaled,y_train)


c:\Users\YASH\anaconda3\envs\cancer\lib\site-packages\sklearn\base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier(max_depth=2, random_state=0)

In [14]:
pred = clf.predict(X_train_scaled)

In [17]:
from sklearn.metrics import accuracy_score

accuracy_score(y_train ,pred )

0.8231611893583725

In [41]:
from sklearn.metrics import f1_score

In [45]:

from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(random_state=0)

In [54]:
clf.fit(X_train_scaled,y_train)

DecisionTreeClassifier(random_state=0)

In [55]:

clf.predict(X_test)

c:\Users\YASH\anaconda3\envs\cancer\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but DecisionTreeClassifier was fitted without feature names
  warnings.warn(


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [61]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [75]:
model.fit(X_train_scaled, y_train)

c:\Users\YASH\anaconda3\envs\cancer\lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

array([[-0.77669002,  0.4332809 , -1.48888985, ..., -0.95645945,
        -0.60205759, -0.48331225],
       [-0.77669002,  0.4332809 , -0.28838434, ...,  0.10645809,
        -0.60205759,  2.06905576],
       [ 0.06736597,  0.4332809 ,  0.91212117, ...,  1.16937564,
        -0.60205759, -0.48331225],
       ...,
       [-0.77669002,  0.4332809 , -0.28838434, ..., -0.95645945,
         1.66097066, -0.48331225],
       [-0.77669002,  0.4332809 ,  1.51237392, ..., -0.95645945,
         1.66097066,  2.06905576],
       [ 0.91142196,  0.4332809 ,  1.51237392, ..., -2.01937699,
        -0.60205759, -0.48331225]])

In [83]:
pred_logistic = model.predict(X_test_scaled)

In [84]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test , pred_logistic)

0.7125

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score ,confusion_matrix , classification_report

In [88]:

rf_model = RandomForestClassifier(n_estimators=10000, random_state=42)
rf_model.fit(X_train_scaled, y_train)
y_pred_rf = rf_model.predict(X_test_scaled)
print("Accuracy:", accuracy_score(y_test, y_pred_rf))



c:\Users\YASH\anaconda3\envs\cancer\lib\site-packages\sklearn\base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


Accuracy: 0.825


In [89]:
from sklearn.model_selection import GridSearchCV

# Define the parameter grid
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Perform Grid Search
grid_search = GridSearchCV(estimator=RandomForestClassifier(random_state=42),
                           param_grid=param_grid, cv=5, n_jobs=-1, verbose=2)
grid_search.fit(X_train_scaled, y_train)

# Get the best parameters
best_params = grid_search.best_params_
print("Best Parameters:", best_params)

# Use the best estimator
best_rf_model = grid_search.best_estimator_

# Predictions
y_pred_best = best_rf_model.predict(X_test_scaled)

# Model evaluation
print("Accuracy:", accuracy_score(y_test, y_pred_best))
print("Classification Report:\n", classification_report(y_test, y_pred_best))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_best))


Fitting 5 folds for each of 81 candidates, totalling 405 fits


c:\Users\YASH\anaconda3\envs\cancer\lib\site-packages\sklearn\base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


Best Parameters: {'max_depth': 10, 'min_samples_leaf': 1, 'min_samples_split': 10, 'n_estimators': 300}
Accuracy: 0.83125
Classification Report:
               precision    recall  f1-score   support

           0       0.73      0.89      0.80        62
           1       0.92      0.80      0.85        98

    accuracy                           0.83       160
   macro avg       0.83      0.84      0.83       160
weighted avg       0.85      0.83      0.83       160

Confusion Matrix:
 [[55  7]
 [20 78]]
